### ISSUE TITLE
How to get tasts assigned to user

### ISSUE THREAD

**Issue by smartmeter** [aspnetboilerplate/taskever#10]
Hi, I want to show the user tasks in his inbox, that are assigned to him, not started by him.

            1       Where is the query thats display the user tasks, the task controller is missing the logic
                     public TaskeverController()
                     {
                              LocalizationSourceName = "Taskever";
                     }
            2       How can I extend this, which table should I use to add a new column?

**Comment by hikalkan** [comment]
Task class has AssignedPersonId, so you can query it.

**Comment by smartmeter** [comment]
thanks :+1:
