### ISSUE TITLE
Inbox like

### ISSUE THREAD

**Issue by smartmeter** [aspnetboilerplate/taskever#11]
This looks like an inbox like task replacement to hangfire, for those who dont need all the hang fire features.

I was trying to extend this and attributes of what was "Tasks", but I am getting database migration errors. Am I doing something wrong.

Was this meant to be extended? I really like this work :+1:

**Comment by x2009again** [comment]
There are many problems with this project, such as Migrations and Recaptcha, there is no page after login.
And No Roles..
![image](https://user-images.githubusercontent.com/5449891/54668524-12585800-4b2a-11e9-85e6-18f3c6cca74e.png)

**Comment by hikalkan** [comment]
We are [not maintaining](https://github.com/aspnetboilerplate/taskever#taskever) this project anymore.

**Comment by x2009again** [comment]
I know，but I can't understand why so many mistakes。
