### ISSUE TITLE
FluentMigrator got a error

### ISSUE THREAD

**Issue by internet5** [aspnetboilerplate/taskever#2]
cannot found “FluentMigrator, Versi
on=1.2.1.0, Culture=neutral, PublicKeyToken=aacfc7de5acabf05”
Cound't found FluentMigrator 1.2.1.0 in everywhere of this project  .

**Comment by Magik3a** [comment]
This is very easy to solve, just update the FluentMigrator to latest stable version (at this point: 1.6.2) and change RunMigrator.bat to "..\..\packages\FluentMigrator.1.6.2\tools\Migrate.exe"
