### ISSUE TITLE
Project Fails to open in VS2013, Update 4

### ISSUE THREAD

**Issue by wildest** [aspnetboilerplate/taskever#4]
I've downloaded the entire directory structure and after building I get a bunch of errors. I've tried to resolve by re-installing nuget packages but keep hitting roadblocks.

Are you still supporting this?

**Comment by MohammadKani** [comment]
i have same problem :(

**Comment by onlinespaces** [comment]
I was able to get a successful build by doing the following in the Package Manger Console:

PM> Update-Package -reinstall Castle.Windsor
PM> Update-Package -reinstall Castle.LoggingFacility
PM> Update-Package -reinstall Microsoft.AspNet.Identity.Core -Pre
PM> Update-Package -reinstall AutoMapper -Pre
PM> Update-Package -reinstall EntityFramework
PM> Update-Package -reinstall EntityFramework.SqlServer -Pre
PM> Update-Package -reinstall FluentMigrator
PM> Update-Package -reinstall FluentNHibernate

Then 
Installed NHibernate with Nuget in Taskserver.Infrastructure.NHibernate

**Comment by onlinespaces** [comment]
Also, I couldn't the RunMigrations.bat to work but was able to create the database by running:
PM > Enable-Migrations
PM> Add-Migration "InitialCreate"

Changing line 80 from  .ForeignKey("dbo.AbpUsers", t => t.FriendUserId, cascadeDelete: true) to  .ForeignKey("dbo.AbpUsers", t => t.FriendUserId, cascadeDelete: false) in the InitialCreate.cs file in the Migrations folder.

I am now getting the following error though:

Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

Source Error: 


Line 11:         {
Line 12:             IocManager.Instance.IocContainer.AddFacility<LoggingFacility>(f => f.UseLog4Net().WithConfig("log4net.config"));
Line 13:             base.Application_Start(sender, e);
Line 14:         }
Line 15:     }

Source File: c:\Users\scollier\Documents\Projects\Personal\taskever\src\Taskever.Web.Mvc\Global.asax.cs    Line: 13

**Comment by MohammedAl-Qaisi** [comment]
thank you @onlinespaces i spent 2 days to solve this problem...
