### ISSUE TITLE
Secutity Issue with project

### ISSUE THREAD

**Issue by dianmushkov** [aspnetboilerplate/taskever#5]
Hi 
When I open my profile, which I have register in taskever.com
this open url
http://www.taskever.com/#user/1857" 

If I change number In this way 

http://www.taskever.com/#user/1855
http://www.taskever.com/#user/1856
http://www.taskever.com/#user/1851

All those request opens Friend Request from which I can see email address for those users
Is that intended behavior?

**Comment by ismcagdas** [comment]
cant reproduce it on http://eventcloud.aspnetboilerplate.com
