### ISSUE TITLE
Incomplete Database Tables

### ISSUE THREAD

**Issue by lanrewajub** [aspnetboilerplate/taskever#9]
Hi,
The following tables were not migrated AbpPermissions,AbpUserRoles, AbpSettings,AbpRoles,,AbpTenants,AbpUserLogins,AbpUserRoles
Regards

**Comment by ismcagdas** [comment]
Will be handled when upgrading to latest ABP https://github.com/aspnetboilerplate/aspnetboilerplate/issues/4601
